#模版信息
name        = taoler
version     = 1.0
framework   = 3.2
description = 中间
author      = Taoler
image       = https://www.aieok.com/storage/SYS_tpl/20250421/06de527353fc9ee7f780b05ba6684f5b.png
web         = https://www.aieok.com
time        = 2025-04-19